# Generated by Django 3.2.3 on 2021-06-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_images_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='slug',
            new_name='product',
        ),
    ]
