# Generated by Django 3.2.4 on 2021-06-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='minamount',
            new_name='min_amount',
        ),
    ]
